version: '3'

includes:
  web:
    taskfile: ./web/Taskfile.yml
    dir: ./web
    optional: true
    aliases:
      - f

env:
  WORLD: World!
vars:
  AWS_PROFILE: pictoria
  AWS_BUCKET: p-logger

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  hello:
    desc: Hello, World!
    cmds:
      - echo ${HELLO} ${WORLD} ${ENV} {{.ENV_CONST}} {{.AWS_PROFILE}}
      - task: date
    vars:
      ENV_CONST: const
    deps: [date]
    env:
      HELLO: Hello,
    aliases:
      - h
  date:
    cmds:
      - date
  aws-init:
    cmds:
      - aws configure --profile {{.AWS_PROFILE}}


