version: '3'

tasks:
  install:
    cmds:
      - pnpm install
  dev:
    cmds:
      - pnpm run dev
  build:
    cmds:
      - pnpm run build
  deploy:
    deps: [build]
    cmds:
      - aws s3 sync dist s3://{{.AWS_BUCKET}} --profile {{.AWS_PROFILE}}
  lint:
    cmds:
      - pnpm run lint
  preview:
    deps: [build]
    cmds:
      - pnpm run preview
