version: '3'

tasks:
  install:
    cmds:
      - pnpm install
  dev:
    cmds:
      - pnpm run dev
  build:
    cmds:
      - pnpm run build
  lint:
    cmds:
      - pnpm run lint
  preview:
    deps: [build]
    cmds:
      - pnpm run preview
